#incbin('test_common1.bin')
add_ascii("DOODBOMB") # just want some random bytes (probably the chat ID for reply etc.)
org(0x10)
add_word(0xFFFFFFFF) # date, just set it to the highest possible value, so it will always be the first letter displayed in the menu
add_word(0xFFFFFFFF)
add_word(0x00002712) # magic sender ID => letter is treated as a special letter
add_word(0X00000000)
add_byte(0x00)
add_byte(0x84)
add_halfword(0x0000)
add_byte(0x02)
add_byte(0x00)
add_byte(0x01)
add_byte(0x00)
org(0x40)
